#!/bin/bash

set -o errexit

set -o pipefail

set -o nounset


worker_reader() {
    celery -A dajngostarter inspect ping
}

until worker_reader; do
    >&2 echo "Celery workers not available :-("
    sleep 1
done

>&2 echo "Celery workers are now ready!... :-)"

exec "$@"

celery -A dajngostarter flower \
    --broker="${CELERY_BROKER_URL}" \